language: csharp
dist: trusty
solution: MakiseSharp.sln
mono: none
dotnet: 1.0.1
notifications:
  email: false
  webhooks:
  - http://13.95.22.78/MakiseSharp/TravisWebhook
  - http://46.22.171.147:2137/MakiseSharp/TravisWebhook
env:
  global:
  - secure: "R6dqYeOny8Kov2et2y0iPj1UGjwL8ValpGMW+x4U+NTa9N7qO/3S3QcaFXFF1+ym+0iMmPdBFXA3+ksXVP/k364HnQf4rpV2YuSGCdqPM3FFu7vtkBZcGlaM3U3XFdnPo1tIUYEG7S0ZGqwsEdNHtY+kCxq26LOgMJQtcatRR/Xa6YTogh7TMUdfvTv67bkcBU94XzD5GRt25H1CGrDhmagcPkoRxrgW8UIJc18yVfA/Q34dV2lmySYw3YOD3IptdKlEgEYeM0JnHIBY91R4xsKH+va+419ZuWbOqbf56HSpPsidyGhLDo28pUQWPHuQWgQDVq/Vs9radSZaSb9f605TSvi1h2xZlTjg/Hlbp4tJszD4NMGNSFfrSHxB+eyO7ShifdnwUbLFFbEA6ef+ybNhPc/BJOndV2EboQc3apuQSvWlF05Vucc9+i2RqXPOsDXIVLkdGg8VXE6Df/q5JHc1PpaHdp9wzb7xExCQv4Pak5W75Zbq0ql4UTAxrYHFMjUIgZVd5xahBqNPLe/kR2kdKkTM+kPp20OPuf+pKfY07P0Q2D5yUsmKF38jPs8zQeqGRUL9iNg0AUxd9/KG2z4w5tfhQs5veOV5pEGAXs0Z9uNfVeCGrVYAATJ2qdKZFXXyyAQl3Q9bybxP79Lxuz6vqDZtdnxlIkrItd5bGFs="
  - secure: "MpyMQxnYHg1zDVCp0+AvV+97BdyAlMVflFXKcYL9+JaLs25KH4jKyf5DaJ6Mk4KvAlTR1ljcuynvbDaunCi35hwqvLKEUHLhPjj1uVXVkOivpLXmaTDOB/WpSNH6VToLY/gIg8o9HgKdw1Ht83x/t4Aohq0yXrQoDTXQMaubiaVqz/JBvSw4nP7DKoWUfqTFNNSxbD6TauGtjIYxB1s18VPqE0xZ9ODN3Dv8MiqsrJfBLq8eNEoaUZyeSGoL5qtVfPqn2omSHAjRL5A5UDHhcjN01U11uh6/jJw3Kwfu0SuzcZePo4dUN4jEmFm75PXSAbGQn3nsKkFTlHGrb+uI3KAJWRTT/gjNMjfiqkI/EZd1mr557UYxPHAlgivpfpGv/xYVxxf1fydEJ3yZKWdnKvxyvOpQOZAyjE1XMXCj86eH5nxPsfo2R5iBMiquRM+Lufe+5GZb11roz1pcdo/fxMvs4DzhzCyJYasfiV2EXrWzRbr7B9qdywYG4Ewp2piHZ3+YmhwBizKy3P4QD81epIl31kJKaYJ+GUO00n5RTIVX2Ue23sgFAktj84mFKWoYSKSXD4Y5/xkDD0oMsjQe2PDd1eC6mov9mOyd/nFjjvc28wCigX1mH0xMFmOvrbWixmQK3lGAds1uIxF55JdZc4TTHICJpcKYz/sFkQXfkHM=" 
  - secure: "a3Q43KjmqXMO584JrRtdvJhRZS6iwnoePSBEd8CE/62ch+vrM8i1amkNkxh5tBo3yKVpXYN/5klKPYwy0PfOXvLHLT5XTYv2/bld3kOn0Urx6YHm0LP+BrJ5/SxKdJtj2PgE10kny76LTxkG1LavpW5rzpzbPCVQCpCGsf+dsh684rw3JXuobSefluDx3FUKX/JYNNGGaGY1PtV8FfpgD4U0qAXHzXnvVAAs6GvuspddBhNhD9+lLnwV+O/E99awGPAeMPx6kzy4gSLzFWeDRR5biRfiWl0GWQmW9CvnJ+KQmF+3yMmVLbCqhzGru8Mpey5Ep/yBpPXdBpI9syJfUocZsUgGTg1HpwiYGtrYBGuz2ddMxVBp1+tsO93MUf/x9oCh3JxiQEtRfO5rO161uPUU7bB/oEnJ8ZyR/kpQ1Q37k4OZgB8SNmYE3ZHatW1fZzj/6HbwjtV+eyYt8gnbxazY7w6f5MDncU0eJ0O9Cv+NDg2ja+jPhm9Z0qdh13R4rS0byV+igWZw2vsmOSSDrmCmvRG1Lye3SG1gfLVuMapXFRQlcIP6wjhK3Q1xK4VZmSXGAoZI5YDEOPegpEzp8p9CLrtjUT4AYHBEfHVCbyQVLBCH1MMw8IV2FfLkeB3+4oN3bjmYH8te2T4c8AIW/opXrBRDrhSnmZfCRvs2zBY="
  - secure: "sDesACfsiV0n3Oai+HnGrGsgK4dyzlh8Bk+JoMuFAeq1IZrxR69AGFtotC/Zw/CkswUNbWQF35QhlDUQM1gcfFnMCtHqmZHpSWPo/8AfMgLxyjbAORe+C5EA+2FEPmz5UGHlwVYY1G+Xvnk4bU1GTbeqLiEPqaVvfzxlp0gZvkWGUHl+AQOeDT8nJCSqfuIb5HccLcAYM571FbvkKoU90lm86gNzeL8YNwi/peF2jwbDpBJwLIHi4Dxf8n6DXtZYsvp08ELdaOghcGQsxtRE3aKyba4XzqC8BBGlJhDkpqau0YU5GhoGJOSPu6Ke2GlmP7W+9ts1ofGm/lDyaVUEw9cbb1iivV1PvAq1p5zCpdzj4zfwVPCrszY783023ZrW6mdiHufnVjaMhoobYyBH8ecq/95rEQu9iULysiTwTATG3F4MyFnCfOqzdsB6ARI1DAZha5gGSps/JN6PEgoCRHxFKNZR8PyeF+M4MU/yrZKJqO+UctBrydfIVUTTvXjXuCdIZdjK9FzR7PIPUVxvi2/Cro4kSxCQvv0tzqw0iHx34nz1aIjETM4tF6AGkUojR8cCY2t8Qys3lcWYN8UpDXhgWU5zcsEYAraTEOa5fg6otS1657yZs5OW0wfCzsgcRtqoi+WEMsHPHnChz67ce1Jt7ORwjJZJW0p9EO2AWBs="
addons:
  apt:
    packages:
    - sshpass
script: ./scripts/build.sh
deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master
