language: csharp
dist: trusty
solution: MakiseSharp.sln
mono: none
dotnet: 1.0.1
notifications:
  email: false
  webhooks:
  - http://13.95.22.78/MakiseSharp/TravisWebhook
  - http://46.22.171.147:2137/MakiseSharp/TravisWebhook
env:
  global:
  - secure: "OoaV6KGfqqSVq1iCU6gw7QeoveBfJsGuHs/I2XNMww7WrPaIjSn3Y9UTvewCJMpReJUS8t7jspZmj8fmMVYI5YdDHB6aT5NaSHagxT1U92wQl6wk1NlgS8JXXO2dkPGVIdPOEebZO2H2o+uuYX8sw1YpIkZ1giN+hosc9lKH2nx5CmAUPyywCtOxXzfLnZufheJWYzi3QnbvX2OoYEotbonZOoqOvuJAeKzc9rSqHyW0yEV2yOlv65ae1PeFL5JWanpM6CfOqYDolQ6hac20/TmbvRN0G5BiAiWd2dc1Qqlu+9KuvoeWMiGDjad+LaBwBbESmM0ckBTMq8tpxEc39BfoLG2FW6E1odpqDPO2xm+ejxUW4GUxy+ocCG5VVBxydmm2rDvMf9vaaVoVzM4mHm+oZvbiqEexnQghV6z2asddrcRlfP1ds9VoBIGr0DbjvvwdbWLnfM/8+Q03XeO1EhehmupubbVF8cJHuDFz/GzZnSrZLXtjLGx7kJvWRRPiQFSpOts2Kw2VdrRbTolkW/pcX4hZdLpYCdys112dNBb8zlKVDPiMUn1dfdgvuaJCHTvd7ygDTce6Vn4nh+qxt5fMZ93cxRp/7KAZEjFtoYSJOw8BiAMIhiwz03ZuTbDi8AKnWD4MfWGmfC6WpMxicTJD2e0qyKFC9XCk7YWY3V4="
  - secure: "nTWrBXkaHMyqiGqoZNdF885lQVFuEVm7/vygvI7MFZ5kPAb50OYtm0FXnp2xhQpVXzOi/H/wkrqbsUQjTcJ2+tNJmWn6gEeAwHLvIlFNzdvJSxfXujHjcnvqI7C0DfAmVNRJAWKzltRhEJGGV8SXDpXS9JV/d2jLfUrbdac2xch43rhL+cdJGjGUib+boS5moFIQujJJrY/ItIERQj3G0ibgARYNyNzMyJxEl6HEa5WsvWcbrYEJN5Wah2iBV8QDy+ZN7/AGjbKjZUiLi6vQLNq2BkDuj5jesg8tDUpFB2pBnxBYTngifUJdS28oGylLOu+7Fb8IbQ6Z79wkFbtOJeaWY7hfQJQfhVlXkTzJCiA/bCtLTmBsN3UoeIfOqHx4jPrmEcL/ElNxd++qsalMp6fPDDvgY6hjUPw8VQChNjBZJ+ICKFhJjUooKS21jbNYneFlsSC2Ozx9ygxBJ2bO24w4T3XR/rZfFzxBsx/qBvgs3qoUrvehuc8gakRKUiaxRQzlM+dsYN2t8RpsUrRxngbxYS9jSGAvbCDjUYBKvRv5y4vMMwSbkHQZGNhqgz5r5Dx7nhOERNYxMKHE2+ui2sglcXqZ0Ls/xxyeROa94hwg2QM5EHpPm4h1jpn9OHGP8SCa9zzcZm1zG5NiLPx+pn6yE8NrbBl76Ps14+xOzfM="
  - secure: "PKzM/COifRVxzoF4X0cUG9klAACMvtgkXzHZJaqw63sA8njQJ0DvsPq8QgkOAw4hglAoR6hwzSqsk+bvPoKVl5zPQHvFh/VL4syKNb6/0A2d9rrIqlq0j4axDlEXysBZT0KjupnoEWnVK4mPHeN5Io3rsRx2GLgdV5Z85bQzKn/gPmbj81v0gP9P3o+VCNLVKbPdv/hOmwgGaQ8oH8V8ap459wKi4zrMMzV7H8yMTV53SZmCqsitvElGZPUXBDGivBWb61PKXlbhiaEDVjTvcvE9KqDIjNct+KD8g9rMbfHET9APEXjvYlrKGEurUPIkUQlTM5tLBN1cgE9YbPwXYFKf7uWqndnTbE5c1oQ1gHOfMUcc5HMEt7rMi//zcYLKy2m+hPQEpJtA3XfpA/RwHSyIpuCsXZvSLZGk/W3QfpZv793Q7di5qmB9BPRoVzAp9ZVXK5j7tANfHGBTycky2MBZCAKJrgBvnw0z5b/f46k2dxmuBCX7Ke28a5JOxJeN1KURKRJU/BSJIO8q5JQKjBawFLdKTKMSrtJyHpsFwJOTkqk1+H0mEIGWrY1nCUgmiPeHiqN62io0sXNnhNOV22O6VPcMjgxTPs6nLYPoTP/wcWvjEOK25XSSQda7bVSwyJCaPNduDdx5R9URBd2YiYjN6FM/lkPCbxPLvwk7SKQ="
  - secure: "g3nnTu1qtMO68O+g6GUaGN5SOd0Qhsc9Qp1msuElyeBClAnR0F1vgYrLbEDhxP97coS2OkvfAWZSe25S6ft7JZrN+iXJahIh9xmpfu3U2ErF079VT+6peZhw69l+LjOe/pU0oakhgLyRLJENN0svEH/4dz6IfXE5k4+iEAbInxyAHZr/OCJUdyZHUeLRwNlduYyasPebXrW5UcinXz0PNy7gX1YbkOoCHcH2O3vRlZn8CoB6anXyB01Quk9P8sbC4AxBXoZ4VY6/yKMicduEDqVBrb8fkNpiddiFUPO7O7NcNfmjghAZLokdGfS3zNo+RcFmbJVpfQJ60z8thgMT2GXQlMmtiHrKSHS/LcVJg3fHJsRmwg+tXEbi7TrOniilx3p47KH777BQiQ8qZXRCOAfEeYqtUGF23YlMjlnyxilM8fN3T0ouJ6Ql2mw+NOo4y2zFgx0eELhOTJprVK2GwXFXB9BcaB1d2VblLsTZWON3hY34Y2tNjP3fLtKIK5jBCxooIOxxZ23++XST3karfYcenZQAdYYyctwMnRZ0bQboWXZm/FK22wArVB8AYz6eKgBX9TZEvW2P0rYHr0XVZQzz3KWOkOnp8ImyhR0ky0iUeIfLe+xLWvrc4LPFI4BENXmklGzsH6Jr8KJo4TV5MwN7069OCW9+pvMreSm2eQ8=" 
addons:
  apt:
    packages:
    - sshpass
script: ./scripts/build.sh
deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master
